### ISSUE TITLE
Capture outbound routing config in emis-access backend

### ISSUE THREAD

**Issue by bloodearnest** [opensafely-core/backend-server#210]
emis-access just manages users, no services.

However, it does need to ensure that its network routing is configured to use its assigned static IP for all outbound traffic.

This looks like adding the following to `/etc/netplan/50-cloud-init.yaml` config for `eth0`:

```
          routes:
              # as per https://docs.digitalocean.com/products/networking/reserved-ips/how-to/outbound-traffic/
              - to: 0.0.0.0/0
                via: 10.16.0.1
```

It may be that emis network access is changing, and we won't need this
